# Generated by Django 2.0.1 on 2018-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_auto_20180416_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='hgmd_phen',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='gnomead_exome_maf',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='GnomeAD Exome Frequency'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='gnomead_genome_maf',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='GnomeAD Genome Frequency'),
        ),
    ]
