# Generated by Django 2.0.1 on 2018-04-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_auto_20180416_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='vep_cds_position',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
