# Generated by Django 2.0.1 on 2018-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_profile_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3credential',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
